const products =[
  {
    id:1,
    name:'t-shirt',
    type:'t-shirt',
    price:120,
    images:[
      {id:1,alt:'img1',image:'Img1',selected:true},
      {id:2,alt:'img2',image:'Img2',selected:false},
      {id:3,alt:'img3',image:'Img3',selected:false},
      {id:4,alt:'img4',image:'Img4',selected:false},
      {id:5,alt:'img5',image:'Img5',selected:false},
    ],
    sizes:[
      {
        id:1,
        type:'s',
        selected:false,
        colors:[
          {
            id:1,
            name:'black',
            instock:true,
            selected:false,
            quantity:17
          },
          {
            id:2,
            name:'blue',
            instock:true,
            selected:false,
            quantity:7
          }
        ]
      },
      {
        id:2,
        type:'m',
        selected:false,
        colors:[
          {
            id:1,
            name:'red',
            instock:true,
            selected:false,
            quantity:21
          },
          {
            id:2,
            name:'blue',
            instock:true,
            selected:false,
            quantity:17
          }
        ]
      },
      {
        id:3,
        type:'l',
        selected:false,
        colors:[
          {
            id:1,
            name:'red',
            instock:true,
            selected:false,
            quantity:15
          },
          {
            id:2,
            name:'blue',
            instock:true,
            selected:false,
            quantity:16
          }
        ]
      },
      {
        id:4,
        type:'xl',
        selected:false,
        colors:[
          {
            id:1,
            name:'red',
            instock:true,
            selected:false,
            quantity:11
          },
          {
            id:2,
            name:'yellow',
            instock:true,
            selected:false,
            quantity:19
          }
        ]
      }
    ]
  }
]
